# Copyright 2023 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

--- !ruby/object:Api::Resource
name: 'ApiProxyDeployment'
base_url: 'organizations/{{org_id}}/environments/{{environment}}/apis/{{proxy_name}}/revisions/{{revision_id}}/deployments'
create_url: 'organizations/{{org_id}}/environments/{{environment}}/apis/{{proxy_name}}/revisions/{{revision_id}}/deployments?override=true&serviceAccount={{service_account}}"'
delete_url: 'organizations/{{org_id}}/environments/{{environment}}/apis/{{proxy_name}}/revisions/{{revision_id}}/deployments'
self_link: 'organizations/{{org_id}}/environments/{{environment}}/apis/{{proxy_name}}/revisions/{{revision_id}}/deployments'
update_url: 'organizations/{{org_id}}/environments/{{environment}}/apis/{{proxy_name}}/revisions/{{revision_id}}/deployments?override=true&serviceAccount={{service_account}}"'
description: |
  TargetServer configuration. TargetServers are used to decouple a proxy TargetEndpoint HTTPTargetConnections from concrete URLs for backend services.
references: !ruby/object:Api::Resource::ReferenceLinks
  guides:
    'Load balancing across backend servers': 'https://cloud.google.com/apigee/docs/api-platform/deploy/load-balancing-across-backend-servers'
  api: 'https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.targetservers/create'
import_format: ['{{env_id}}/targetservers/{{name}}', '{{env_id}}/{{name}}']
async: !ruby/object:Api::OpAsync
  operation: !ruby/object:Api::OpAsync::Operation
    path: 'name'
    base_url: '{{op_id}}'
    wait_ms: 1000
  result: !ruby/object:Api::OpAsync::Result
    path: 'response'
    resource_inside_response: true
  status: !ruby/object:Api::OpAsync::Status
    path: 'done'
    complete: true
    allowed:
      - true
      - false
  error: !ruby/object:Api::OpAsync::Error
    path: 'error'
    message: 'message'
skip_sweeper: true
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: 'apigee_target_server_test_basic'
    primary_resource_id: 'apigee_target_server'
    vars:
      project_id: 'my-project'
      environment_name: 'my-environment-name'
      target_server: 'my-target-server'
    test_env_vars:
      org_id: :ORG_ID
      billing_account: :BILLING_ACCT
    skip_test: true
  - !ruby/object:Provider::Terraform::Examples
    name: 'apigee_target_server_test'
    primary_resource_id: 'apigee_target_server'
    test_env_vars:
      org_id: :ORG_ID
      billing_account: :BILLING_ACCT
    skip_docs: true
timeouts: !ruby/object:Api::Timeouts
  insert_minutes: 20
  update_minutes: 20
  delete_minutes: 20

custom_code: !ruby/object:Provider::Terraform::CustomCode
  custom_import: templates/terraform/custom_import/apigee_api_proxy_deployment.go.erb
  custom_create: templates/terraform/custom_create/apigee_api_proxy_deployment_create.go
  custom_update: templates/terraform/custom_update/apigee_api_proxy_deployment_update.go
autogen_async: true
parameters:
  - !ruby/object:Api::Type::String
    name: 'org_id'
    description: |
      The Apigee environment group associated with the Apigee environment,
      in the format `organizations/{{org_name}}/environments/{{env_name}}`.
    required: true
    immutable: true
    url_param_only: true
  - !ruby/object:Api::Type::String
    name: 'environment'
    description: |
      The Apigee environment group associated with the Apigee environment,
      in the format `organizations/{{org_name}}/environments/{{env_name}}`.
    required: true
    immutable: true
    url_param_only: true
  - !ruby/object:Api::Type::String
    name: 'proxy_name'
    description: |
      The Apigee environment group associated with the Apigee environment,
      in the format `organizations/{{org_name}}/environments/{{env_name}}`.
    required: true
    immutable: true
    url_param_only: true
  - !ruby/object:Api::Type::String
    name: 'revision_id'
    description: |
      The Apigee environment group associated with the Apigee environment,
      in the format `organizations/{{org_name}}/environments/{{env_name}}`.
    required: true
    immutable: true
    url_param_only: true  
  - !ruby/object:Api::Type::Boolean
    name: 'override'
    description: |
      Flag that specifies whether the new deployment replaces other deployed revisions of the API proxy in the environment.
    default_value: false
    url_param_only: true  
  - !ruby/object:Api::Type::Boolean
    name: 'sequencedRollout'
    description: |
      Flag that specifies whether to enable sequenced rollout.
    url_param_only: true
  - !ruby/object:Api::Type::String
    name: 'serviceAccount'
    description: |
      Google Cloud IAM service account.              
    url_param_only: true
properties:




